version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: colinxfleming/dcaf_case_management:latest
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      mongohost: db
    env_file:
      - web-variables.env
  db:
    image: mongo
    ports:
      - "27017:27017"
