# Empty
version: 2

jobs:
  build:
    parallelism: 3
    working_directory: ~/abortioneering
    docker:
      - image: circleci/ruby:2.4.3-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
      - image: circleci/mongo:latest

    steps:
      - checkout
      - run: 
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - dcaf_case_management-{{ checksum "Gemfile.lock" }}
            - dcaf_case_management-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: dcaf_case_management-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rake knapsack:minitest
      - run: gem install --no-rdoc brakeman; bundle exec brakeman --exit-on-warn .
      - run: gem install --no-rdoc ruby_audit; bundle exec ruby-audit check
      - run: gem install --no-rdoc bundler-audit; bundle-audit update; bundle-audit check
  deployment:
    steps:
      - run: yes | gem install --no-rdoc brakeman-pro --source $BRAKEMAN_PRO_URL; bundle exec brakeman --exit-on-warn .
      - run: bundle exec rake assets:clobber assets:precompile
      - run: "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow" # necessary due to moving to an organization
      - run: git push git@heroku.com:dcaf-cmapp-staging.git $CIRCLE_SHA1:master
      - run: docker build -t colinxfleming/dcaf_case_management -f .docker/Dockerfile . && docker login -e "$DOCKEREMAIL" -u "$DOCKERLOGIN" -p "$DOCKERPASS" && docker push colinxfleming/dcaf_case_management

# general:
  # artifacts:
    # - "tmp/screenshots/"

workflows:
  version: 2
  dcaf-workflow:
    jobs:
      - build
      - deployment:
        filters:
          branches:
            only: master
        requires:
          - build
